#!/bin/sh

git submodule init &&
git submodule update &&
cd libapps &&
LIBDOT_SEARCH_PATH=`pwd` ./libdot/bin/concat.sh -i ./hterm/concat/hterm_all.concat -o ../public/hterm_all.js &&
cd - &&
npm install
